'use client'

import { useState } from 'react'
import { Volume2, Mic } from 'lucide-react'
import { cn } from '@/lib/utils/cn'
import type { AiAudioMode, MusicMood } from '@/types'

interface StepAudioProps {
    aiAudioMode: AiAudioMode
    onChange: (mode: AiAudioMode) => void
    voiceId: string
    onVoiceChange: (id: string) => void
    musicMood: MusicMood
    onMusicMoodChange: (mood: MusicMood) => void
    musicVolume: number
    onMusicVolumeChange: (vol: number) => void
}

const VOICE_PRESETS = [
    { id: 'ryan', name: 'Ryan', desc: 'Confident Male' },
    { id: 'sarah', name: 'Sarah', desc: 'Warm Female' },
    { id: 'jake', name: 'Jake', desc: 'Deep Narrator' },
    { id: 'maya', name: 'Maya', desc: 'Energetic Female' },
    { id: 'alex', name: 'Alex', desc: 'Casual Male' },
    { id: 'luna', name: 'Luna', desc: 'Smooth Female' },
]

const MUSIC_MOODS: MusicMood[] = ['upbeat', 'dark', 'motivational', 'calm', 'mystery']

function StepAudio({
    aiAudioMode,
    onChange,
    voiceId,
    onVoiceChange,
    musicMood,
    onMusicMoodChange,
    musicVolume,
    onMusicVolumeChange,
}: StepAudioProps) {
    return (
        <div className="max-w-[720px] mx-auto pt-10">
            <h2 className="text-[22px] font-bold text-[var(--text-primary)]">
                Audio Setup
            </h2>
            <p className="text-[13px] text-[var(--text-secondary)] mt-1 mb-8">
                Your AI video comes with generated audio. Choose how you want to handle it.
            </p>

            <div className="grid grid-cols-2 gap-4">
                {/* Keep AI Audio */}
                <button
                    type="button"
                    onClick={() => onChange('keep_ai')}
                    className={cn(
                        'rounded-[12px] border-2 p-5 text-left transition-all duration-200',
                        aiAudioMode === 'keep_ai'
                            ? 'border-emerald-500 bg-emerald-500/5'
                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                    )}
                >
                    <Volume2
                        size={28}
                        className={cn(
                            'mb-3',
                            aiAudioMode === 'keep_ai' ? 'text-emerald-500' : 'text-[var(--text-dim)]'
                        )}
                    />
                    <h3 className="text-[15px] font-bold text-[var(--text-primary)] mb-2">
                        Keep AI Audio
                    </h3>
                    <p className="text-[13px] text-[var(--text-secondary)] mb-3 leading-relaxed">
                        Use the audio generated by Sora 2 alongside the video. Natural,
                        in-context sound that matches the visuals.
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                        {['Zero processing', 'Instant', 'Authentic'].map((tag) => (
                            <span
                                key={tag}
                                className="text-[10px] font-medium px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-500"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>
                </button>

                {/* Replace Audio */}
                <button
                    type="button"
                    onClick={() => onChange('replace')}
                    className={cn(
                        'rounded-[12px] border-2 p-5 text-left transition-all duration-200',
                        aiAudioMode === 'replace'
                            ? 'border-[var(--accent)] bg-[var(--accent-subtle)]'
                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                    )}
                >
                    <Mic
                        size={28}
                        className={cn(
                            'mb-3',
                            aiAudioMode === 'replace' ? 'text-[var(--accent)]' : 'text-[var(--text-dim)]'
                        )}
                    />
                    <h3 className="text-[15px] font-bold text-[var(--text-primary)] mb-2">
                        Replace with Voice + Music
                    </h3>
                    <p className="text-[13px] text-[var(--text-secondary)] mb-3 leading-relaxed">
                        Strip the AI audio and add a custom voiceover
                        narrating your topic, mixed with background music.
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                        {['Custom voice', 'Music', 'Subtitles'].map((tag) => (
                            <span
                                key={tag}
                                className="text-[10px] font-medium px-2 py-1 rounded-full bg-[var(--accent)]/10 text-[var(--accent)]"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>
                </button>
            </div>

            {/* Expanded options for Replace mode */}
            {aiAudioMode === 'replace' && (
                <div className="mt-6 space-y-5 animate-in slide-in-from-top-2 duration-300">
                    {/* Voice selector */}
                    <div>
                        <p className="text-[13px] font-semibold text-[var(--text-primary)] mb-3">
                            Voice
                        </p>
                        <div className="grid grid-cols-3 gap-2">
                            {VOICE_PRESETS.map((voice) => (
                                <button
                                    key={voice.id}
                                    type="button"
                                    onClick={() => onVoiceChange(voice.id)}
                                    className={cn(
                                        'rounded-[8px] border p-3 text-left transition-all duration-150',
                                        voiceId === voice.id
                                            ? 'border-[var(--accent)] bg-[var(--accent-subtle)]'
                                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                                    )}
                                >
                                    <span className="text-[13px] font-semibold text-[var(--text-primary)] block">
                                        {voice.name}
                                    </span>
                                    <span className="text-[11px] text-[var(--text-dim)]">
                                        {voice.desc}
                                    </span>
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Music mood */}
                    <div>
                        <p className="text-[13px] font-semibold text-[var(--text-primary)] mb-3">
                            Music Mood
                        </p>
                        <div className="flex flex-wrap gap-2">
                            {MUSIC_MOODS.map((mood) => (
                                <button
                                    key={mood}
                                    type="button"
                                    onClick={() => onMusicMoodChange(mood)}
                                    className={cn(
                                        'rounded-full px-4 py-2 text-[12px] font-medium capitalize transition-all duration-150',
                                        musicMood === mood
                                            ? 'bg-[var(--accent)] text-white'
                                            : 'bg-[var(--card)] border border-[var(--border)] text-[var(--text-secondary)] hover:border-[var(--accent-border)]'
                                    )}
                                >
                                    {mood}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Music volume */}
                    <div>
                        <div className="flex items-center justify-between mb-2">
                            <p className="text-[13px] font-semibold text-[var(--text-primary)]">
                                Music Volume
                            </p>
                            <span className="text-[12px] text-[var(--text-dim)] font-mono">
                                {Math.round(musicVolume * 100)}%
                            </span>
                        </div>
                        <input
                            type="range"
                            min={0}
                            max={1}
                            step={0.05}
                            value={musicVolume}
                            onChange={(e) => onMusicVolumeChange(parseFloat(e.target.value))}
                            className="w-full accent-[var(--accent)]"
                        />
                    </div>
                </div>
            )}
        </div>
    )
}

export { StepAudio }
