'use client'

import { useState, useEffect, useRef } from 'react'
import { Volume2, Mic, PlayCircle, PauseCircle } from 'lucide-react'
import { cn } from '@/lib/utils/cn'
import { VOICES } from '@/lib/utils/constants'
import type { AiAudioMode, MusicMood } from '@/types'

interface AdminMusicTrack {
    id: string
    name: string
    mood: string
    fileUrl: string
}

interface StepAudioProps {
    aiAudioMode: AiAudioMode
    onChange: (mode: AiAudioMode) => void
    voiceId: string
    onVoiceChange: (id: string) => void
    musicMood: string // Now accepts either mood string OR standard fileUrl
    onMusicMoodChange: (moodOrUrl: string) => void
    musicVolume: number
    onMusicVolumeChange: (vol: number) => void
}

// Use the canonical English voices from constants — same list as the image-stack voice step
const AI_VOICE_PRESETS = VOICES.filter((v) => v.language === 'English')

function StepAudio({
    aiAudioMode,
    onChange,
    voiceId,
    onVoiceChange,
    musicMood,
    onMusicMoodChange,
    musicVolume,
    onMusicVolumeChange,
}: StepAudioProps) {
    const [tracks, setTracks] = useState<AdminMusicTrack[]>([])
    const [playingUrl, setPlayingUrl] = useState<string | null>(null)
    const audioRef = useRef<HTMLAudioElement | null>(null)

    useEffect(() => {
        fetch('/api/admin/music?public=true')
            .then(res => res.json())
            .then(data => {
                if (data.success) {
                    setTracks(data.data)
                }
            })
            .catch(() => {})

        if (typeof window !== 'undefined' && !audioRef.current) {
            audioRef.current = new Audio()
            audioRef.current.onended = () => setPlayingUrl(null)
        }
        
        return () => {
             if (audioRef.current) {
                 audioRef.current.pause()
                 audioRef.current = null
             }
        }
    }, [])

    const handlePlay = (url: string, e: React.MouseEvent) => {
        e.stopPropagation()
        if (!audioRef.current) return

        if (playingUrl === url) {
            audioRef.current.pause()
            setPlayingUrl(null)
        } else {
            audioRef.current.src = url
            audioRef.current.play().catch(() => {})
            setPlayingUrl(url)
        }
    }
    return (
        <div className="max-w-[720px] mx-auto pt-10">
            <h2 className="text-[22px] font-bold text-[var(--text-primary)]">
                Audio Setup
            </h2>
            <p className="text-[13px] text-[var(--text-secondary)] mt-1 mb-8">
                Your AI video comes with generated audio. Choose how you want to handle it.
            </p>

            <div className="grid grid-cols-2 gap-4">
                {/* Keep AI Audio */}
                <button
                    type="button"
                    onClick={() => onChange('keep_ai')}
                    className={cn(
                        'rounded-[12px] border-2 p-5 text-left transition-all duration-200',
                        aiAudioMode === 'keep_ai'
                            ? 'border-emerald-500 bg-emerald-500/5'
                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                    )}
                >
                    <Volume2
                        size={28}
                        className={cn(
                            'mb-3',
                            aiAudioMode === 'keep_ai' ? 'text-emerald-500' : 'text-[var(--text-dim)]'
                        )}
                    />
                    <h3 className="text-[15px] font-bold text-[var(--text-primary)] mb-2">
                        Keep AI Audio
                    </h3>
                    <p className="text-[13px] text-[var(--text-secondary)] mb-3 leading-relaxed">
                        Use the audio generated by Sora 2 alongside the video. Natural,
                        in-context sound that matches the visuals.
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                        {['Zero processing', 'Instant', 'Authentic'].map((tag) => (
                            <span
                                key={tag}
                                className="text-[10px] font-medium px-2 py-1 rounded-full bg-emerald-500/10 text-emerald-500"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>
                </button>

                {/* Replace Audio */}
                <button
                    type="button"
                    onClick={() => onChange('replace')}
                    className={cn(
                        'rounded-[12px] border-2 p-5 text-left transition-all duration-200',
                        aiAudioMode === 'replace'
                            ? 'border-[var(--accent)] bg-[var(--accent-subtle)]'
                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                    )}
                >
                    <Mic
                        size={28}
                        className={cn(
                            'mb-3',
                            aiAudioMode === 'replace' ? 'text-[var(--accent)]' : 'text-[var(--text-dim)]'
                        )}
                    />
                    <h3 className="text-[15px] font-bold text-[var(--text-primary)] mb-2">
                        Replace with Voice + Music
                    </h3>
                    <p className="text-[13px] text-[var(--text-secondary)] mb-3 leading-relaxed">
                        Strip the AI audio and add a custom voiceover
                        narrating your topic, mixed with background music.
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                        {['Custom voice', 'Music', 'Subtitles'].map((tag) => (
                            <span
                                key={tag}
                                className="text-[10px] font-medium px-2 py-1 rounded-full bg-[var(--accent)]/10 text-[var(--accent)]"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>
                </button>
            </div>

            {/* Expanded options for Replace mode */}
            {aiAudioMode === 'replace' && (
                <div className="mt-6 space-y-5 animate-in slide-in-from-top-2 duration-300">
                    {/* Voice selector */}
                    <div>
                        <p className="text-[13px] font-semibold text-[var(--text-primary)] mb-3">
                            Voice
                        </p>
                        <div className="grid grid-cols-3 gap-2">
                            {AI_VOICE_PRESETS.map((voice) => (
                                <button
                                    key={voice.id}
                                    type="button"
                                    onClick={() => onVoiceChange(voice.id)}
                                    className={cn(
                                        'rounded-[8px] border p-3 text-left transition-all duration-150',
                                        voiceId === voice.id
                                            ? 'border-[var(--accent)] bg-[var(--accent-subtle)]'
                                            : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)]'
                                    )}
                                >
                                    <span className="text-[13px] font-semibold text-[var(--text-primary)] block">
                                        {voice.name}
                                    </span>
                                    <span className="text-[11px] text-[var(--text-dim)]">
                                        {voice.accent} &bull; {voice.gender}
                                    </span>
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Music selector */}
                    <div>
                        <div className="flex justify-between items-end mb-3">
                            <p className="text-[13px] font-semibold text-[var(--text-primary)]">
                                Background Music
                            </p>
                        </div>
                        
                        {tracks.length === 0 ? (
                            <div className="text-[12px] text-[var(--text-dim)] italic">Loading music library...</div>
                        ) : (
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-[220px] overflow-y-auto pr-2 custom-scrollbar">
                                {tracks.map((track) => {
                                    const isSelected = musicMood === track.fileUrl
                                    const isPlaying = playingUrl === track.fileUrl

                                    return (
                                        <div
                                            key={track.id}
                                            onClick={() => onMusicMoodChange(track.fileUrl)}
                                            className={cn(
                                                'relative flex items-center justify-between p-3 rounded-[10px] border transition-all cursor-pointer group',
                                                isSelected
                                                    ? 'border-[var(--accent)] bg-[var(--accent-subtle)]'
                                                    : 'border-[var(--border)] bg-[var(--card)] hover:border-[var(--accent-border)] hover:bg-[#1f1f2e]'
                                            )}
                                        >
                                            <div className="flex items-center gap-3 overflow-hidden">
                                                <button
                                                    onClick={(e) => handlePlay(track.fileUrl, e)}
                                                    className={cn(
                                                        'flex-shrink-0 flex items-center justify-center w-8 h-8 rounded-full transition-colors',
                                                        isPlaying
                                                            ? 'bg-[var(--accent)] text-white'
                                                            : 'bg-[var(--bg-muted)] text-[var(--text-secondary)] group-hover:text-[var(--text-primary)] group-hover:bg-[#2a2a3e]'
                                                    )}
                                                >
                                                    {isPlaying ? <PauseCircle size={18} /> : <PlayCircle size={18} />}
                                                </button>
                                                <div className="flex flex-col overflow-hidden">
                                                    <span className="text-[13px] font-semibold text-[var(--text-primary)] truncate">
                                                        {track.name}
                                                    </span>
                                                    <span className="text-[11px] text-[var(--text-dim)] uppercase tracking-wider">
                                                        {track.mood}
                                                    </span>
                                                </div>
                                            </div>

                                            {/* Selection indicator */}
                                            {isSelected && (
                                                <div className="flex-shrink-0 w-4 h-4 rounded-full bg-[var(--accent)] flex items-center justify-center ml-2">
                                                    <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 12 12">
                                                        <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                                                    </svg>
                                                </div>
                                            )}
                                        </div>
                                    )
                                })}
                            </div>
                        )}
                    </div>

                    {/* Music volume */}
                    <div>
                        <div className="flex items-center justify-between mb-2">
                            <p className="text-[13px] font-semibold text-[var(--text-primary)]">
                                Music Volume
                            </p>
                            <span className="text-[12px] text-[var(--text-dim)] font-mono">
                                {Math.round(musicVolume * 100)}%
                            </span>
                        </div>
                        <input
                            type="range"
                            min={0}
                            max={1}
                            step={0.05}
                            value={musicVolume}
                            onChange={(e) => onMusicVolumeChange(parseFloat(e.target.value))}
                            className="w-full accent-[var(--accent)]"
                        />
                    </div>
                </div>
            )}
        </div>
    )
}

export { StepAudio }
